[[redirects]]
  from = "/index.html"
  to = "https://cretecreationsllc.com/"
  status = 301
  force = true

[[redirects]]
  from = "/gallery.html"
  to = "https://cretecreationsllc.com/gallery"
  status = 301
  force = true

[[redirects]]
  from = "/bentonville.html"
  to = "https://cretecreationsllc.com/bentonville"
  status = 301
  force = true

[[redirects]]
  from = "/polished-concrete.html"
  to = "https://cretecreationsllc.com/polished-concrete"
  status = 301
  force = true
